exports.api = {
  DATABASE_URL: process.env.DATABASE_URL,
  BASE_URL: process.env.DATABASE_URL,
  AWSAccessKeyId: process.env.AWSAccessKeyId,
  AWSSecretKey: process.env.AWSSecretKey,
  bucketName: process.env.bucketName,
  S3FileUploadLimit: process.env.S3FileUploadLimit,
  auth0ClientId: process.env.auth0ClientId,
  auth0ClientSecret: process.env.auth0ClientSecret,
  auth0Domain: process.env.auth0Domain,
  auth0Connection: process.env.auth0Connection,
  resourceServerId: process.env.resourceServerId,
  resourceServerIdentifier: process.env.resourceServerIdentifier,
  stripeKey: process.env.stripeKey,
  stripeSecret: process.env.stripeSecret,
  stripeWebhookSecret: process.env.stripeWebhookSecret,
  stripeApiVersion: process.env.stripeApiVersion,
  twillioAccountSid: process.env.twillioAccountSid,
  twillioAuthToken: process.env.twillioAuthToken,
  twillioServiceId: process.env.twillioServiceId,
  deliveryTime: 45,
  paymentMethodTypes: ['card'],
  currency: 'usd',
  currencyMinimumUnit: 100,
  timeSlotInterval: 15,
  orderPadding: 5,
  crewQueueTime: 45,
};
